[View in Colaboratory](https://colab.research.google.com/github/jacklee20151/crm/blob/master/test.ipynb)

In [4]:
#!/usr/bin/python
#coding=utf-8
from sklearn.tree import DecisionTreeRegressor
import numpy as np
from sklearn import tree
from sklearn import svm
from sklearn.linear_model import SGDClassifier
import numpy as np
def f(x1, x2):
    y = 0.5 * np.sin(x1) + 0.5 * np.cos(x2)  + 0.1 * x1 + 3
    return y

def load_data():
    x1_train = np.linspace(0,50,500)
    x2_train = np.linspace(-10,10,500)
    data_train = np.array([[x1,x2,f(x1,x2) + (np.random.random(1)-0.5)] for x1,x2 in zip(x1_train, x2_train)])
    x1_test = np.linspace(0,50,100)+ 0.5 * np.random.random(100)
    x2_test = np.linspace(-10,10,100) + 0.02 * np.random.random(100)
    data_test = np.array([[x1,x2,f(x1,x2)] for x1,x2 in zip(x1_test, x2_test)])
    return data_train, data_test

def main(_):
    data = load_data()
    #print(data)
    x_train = data[0]
    clf = DecisionTreeRegressor()
    
    
    X = [[0, 0,5,6,6,7,777,6], [2, 2,9,0,11,33,22,66]]
    y = [0.5, 2.5]
    clf1 = tree.DecisionTreeRegressor()
    clf1 = clf.fit(X, y)
    a= clf1.predict([[1, 5,6,6,7,4,6,3]])
    print(a)
    
    
    X2 = [[0, 0,6,7], [1, 1,6,5], [5, 6,7,8], [6, 6,7,8]]
    y2 = [0, 1,5,7]
    clf2 = svm.SVR()
    clf2.fit(X2, y2)
    b= clf2.predict([[0,0,7,9]])
    print(b)
    print(clf2.support_vectors_)
    
    
    X = [[0., 0.], [1., 1.]]
    y = [0, 1]
    clf3 = SGDClassifier(loss="hinge", penalty="l2")
    clf3.fit(X, y)
    c = clf3.predict([[2., 2.]])
    print(c)
    print(clf3.coef_ )
    print(clf3.intercept_)

    aa = np.array([[1,2,3],[3,4,5]])
    print(aa)
    bb = np.array([[9,8], [7,6], [10,11]])
    print(bb)
 




    #clf.fit(x_train, y_train)

if __name__ == '__main__':
    main(0)

[0.5]
[2.42700832]
[[0. 0. 6. 7.]
 [1. 1. 6. 5.]
 [5. 6. 7. 8.]
 [6. 6. 7. 8.]]
[1]
[[9.91080278 9.91080278]]
[-9.99002993]
[[1 2 3]
 [3 4 5]]
[[ 9  8]
 [ 7  6]
 [10 11]]


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
